[[themes]]
id = "dark"
display_name = "Dark"
background = "#000000"
user_prefix = "#00bcd4,bold"
user_text = "#00bcd4"
assistant_text = "#e5e7eb"
system_text = "#6b7280"
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#7dd3fc"
app_info_text = "#bfdbfe"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#fde047"
app_warning_text = "#facc15"
app_error_prefix = "⛔  "
app_error_prefix_style = "#fca5a5"
app_error_text = "#fca5a5"
title = "#9ca3af"
streaming_indicator = "#ffffff"
selection_highlight = "bg:#1f2937"
input_border = "#4b5563"
input_title = "#9ca3af"
input_text = "#e5e7eb"
input_cursor_modifiers = "reversed"
md_h1 = "#ffffff,bold"
md_h2 = "#e5e7eb,bold"
md_h3 = "#e5e7eb"
md_h4 = "#d1d5db"
md_inline_code = "#e5e7eb,reversed"
md_blockquote_text = "#6b7280,italic"
md_list_marker = "#9ca3af"
md_link = "#93c5fd,underline"
md_rule = "#374151"
md_codeblock_text = "#cbd5e1"

[[themes]]
id = "light"
display_name = "Light"
background = "#ffffff"
user_prefix = "#2563eb,bold"
user_text = "#2563eb"
assistant_text = "#111827"
system_text = "#6b7280"
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#2563eb"
app_info_text = "#1d4ed8"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#d97706"
app_warning_text = "#ca8a04"
app_error_prefix = "⛔  "
app_error_prefix_style = "red"
app_error_text = "red"
title = "#374151"
streaming_indicator = "#111827"
selection_highlight = "bg:#dbeafe"
input_border = "#111827"
input_title = "#374151"
input_text = "#111827"
input_cursor_modifiers = "reversed"
md_h1 = "#111827,bold"
md_h2 = "#1f2937,bold"
md_h3 = "#374151"
md_h4 = "#4b5563"
md_inline_code = "#111827,reversed"
md_blockquote_text = "#6b7280,italic"
md_list_marker = "#374151"
md_link = "#2563eb,underline"
md_rule = "#9ca3af"
md_codeblock_text = "#374151"
md_codeblock_bg = "#f3f4f6"

[[themes]]
id = "dracula"
display_name = "Dracula"
background = "#282a36"
user_prefix = "#ff79c6,bold"
user_text = "#ff79c6"
assistant_text = "#f8f8f2"
system_text = "#6272a4"
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#8be9fd"
app_info_text = "#bdf6ff"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#ffb86c"
app_warning_text = "#ffaa00"
app_error_prefix = "⛔  "
app_error_prefix_style = "#ff5555"
app_error_text = "#ff7979"
title = "#bd93f9"
streaming_indicator = "#bd93f9"
selection_highlight = "bg:#44475a"
input_border = "#bd93f9"
input_title = "#bd93f9"
input_text = "#f8f8f2"
input_cursor_modifiers = "reversed"
md_h1 = "#f8f8f2,bold"
md_h2 = "#f8f8f2,bold"
md_h3 = "#f8f8f2"
md_h4 = "#bd93f9"
md_inline_code = "#f8f8f2,reversed"
md_blockquote_text = "#6272a4,italic"
md_list_marker = "#bd93f9"
md_link = "#8be9fd,underline"
md_rule = "#44475a"
md_codeblock_text = "#f8f8f2"
md_codeblock_bg = "#21222c"

[[themes]]
id = "solarized-dark"
display_name = "Solarized Dark"
background = "#002b36"          # base03
user_prefix = "#268bd2,bold"     # blue
user_text = "#268bd2"
assistant_text = "#93a1a1"       # base1
system_text = "#586e75"          # base01
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#2aa198"
app_info_text = "#93a1a1"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#b58900"
app_warning_text = "#cb4b16"
app_error_prefix = "⛔  "
app_error_prefix_style = "#dc322f"
app_error_text = "#dc322f"
title = "#2aa198"                # cyan
streaming_indicator = "#2aa198"
selection_highlight = "bg:#003f4d"
input_border = "#586e75"         # base01
input_title = "#586e75"
input_text = "#eee8d5"           # base2
input_cursor_modifiers = "reversed"
md_h1 = "#eee8d5,bold"
md_h2 = "#93a1a1,bold"
md_h3 = "#93a1a1"
md_h4 = "#839496"
md_inline_code = "#93a1a1,reversed"
md_blockquote_text = "#586e75,italic"
md_list_marker = "#2aa198"
md_link = "#268bd2,underline"
md_rule = "#073642"
md_codeblock_text = "#839496"       # base0
md_codeblock_bg = "#073642"         # base02

[[themes]]
id = "solarized-light"
display_name = "Solarized Light"
background = "#fdf6e3"          # base3
user_prefix = "#268bd2,bold"     # blue
user_text = "#268bd2"
assistant_text = "#586e75"       # base01
system_text = "#657b83"          # base00
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#268bd2"
app_info_text = "#1f6fbf"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#b58900"
app_warning_text = "#b45309"
app_error_prefix = "⛔  "
app_error_prefix_style = "#dc2626"
app_error_text = "#dc2626"
title = "#586e75"                # base01
streaming_indicator = "#586e75"
selection_highlight = "bg:#e1f5f8"
input_border = "#657b83"         # base00
input_title = "#657b83"
input_text = "#073642"           # base02
input_cursor_modifiers = "reversed"
md_h1 = "#073642,bold"
md_h2 = "#586e75,bold"
md_h3 = "#586e75"
md_h4 = "#657b83"
md_inline_code = "#586e75,reversed"
md_blockquote_text = "#657b83,italic"
md_list_marker = "#2aa198"
md_link = "#268bd2,underline"
md_rule = "#93a1a1"
md_codeblock_text = "#657b83"       # base00
md_codeblock_bg = "#eee8d5"         # base2

[[themes]]
id = "high-contrast-dark"
display_name = "High Contrast Dark"
background = "#000000"
user_prefix = "#00e5ff,bold"
user_text = "#00e5ff"
assistant_text = "#ffffff"
system_text = "#9ca3af"
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#38bdf8"
app_info_text = "#0ea5e9"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#facc15"
app_warning_text = "#f59e0b"
app_error_prefix = "⛔  "
app_error_prefix_style = "#ef4444"
app_error_text = "#ef4444"
title = "#facc15"
streaming_indicator = "#f97316"
selection_highlight = "bg:#1f2937"
input_border = "#facc15"
input_title = "#facc15"
input_text = "#e5e7eb"
input_cursor_modifiers = "reversed"
md_h1 = "#ffffff,bold"
md_h2 = "#ffffff,bold"
md_h3 = "#ffffff"
md_h4 = "#facc15"
md_inline_code = "#ffffff,reversed"
md_blockquote_text = "#9ca3af,italic"
md_list_marker = "#facc15"
md_link = "#00e5ff,underline"
md_rule = "#facc15"
md_codeblock_text = "#ffffff"
md_codeblock_bg = "#111111"

[[themes]]
id = "paper"
display_name = "Paper"
background = "#faf6f0"
user_prefix = "#1f6feb,bold"
user_text = "#1f6feb"
assistant_text = "#111827"
system_text = "#6b7280"
app_info_prefix = "ℹ️  "
app_info_prefix_style = "#1f6feb"
app_info_text = "#1d4ed8"
app_warning_prefix = "⚠️  "
app_warning_prefix_style = "#d97706"
app_warning_text = "#b45309"
app_error_prefix = "⛔  "
app_error_prefix_style = "#b91c1c"
app_error_text = "#b91c1c"
title = "#374151"
streaming_indicator = "#111827"
selection_highlight = "bg:#e0f2fe"
input_border = "#111827"
input_title = "#374151"
input_text = "#1f2937"
input_cursor_modifiers = "reversed"
md_h1 = "#111827,bold"
md_h2 = "#374151,bold"
md_h3 = "#374151"
md_h4 = "#6b7280"
md_inline_code = "#111827,reversed"
md_blockquote_text = "#6b7280,italic"
md_list_marker = "#374151"
md_link = "#1f6feb,underline"
md_rule = "#d1d5db"
md_codeblock_text = "#1f2937"
md_codeblock_bg = "#f0ebe0"
