Output recordings/assistant-edit.mp4
Source lib/preamble.tape

Type "Hi!"
Enter
Source lib/wait-turn.tape

Type "What's your favorite food?"
Enter
Source lib/wait-turn.tape

Type "We can select and edit the assistant's response with Ctrl+X."
Source lib/del-input.tape

Ctrl+X
Sleep 1
Enter
PageUp
Sleep 1
Ctrl+A
Sleep 1
Ctrl+K
Sleep 0.5
Ctrl+K
Sleep 0.5
Ctrl+K
Sleep 0.5
Ctrl+K
Sleep 0.5
Type "Rocks."
Sleep 1
Enter

Type "Why?"
Source lib/wait-turn.tape
Sleep 3