Output recordings/user-edit.mp4
Source lib/preamble.tape

Type "Hi!"
Enter
Source lib/wait-turn.tape

Type "We can select and edit our messages with Ctrl+P."
Source lib/del-input.tape

Type "I am eating pizza."
Enter
Source lib/wait-turn.tape

Ctrl+P
Sleep 0.5
Enter
Backspace 6
Type "salad."
Enter
Source lib/wait-turn.tape

Ctrl+P
Sleep 0.5
Enter
Backspace 6
Type "rocks."
Enter
Source lib/wait-turn.tape

Sleep 3